### ISSUE TITLE
This utility might be incorrectly licensed

### ISSUE THREAD

**Issue by bitemyapp** [jpvillaisaza/licensor#21]
https://en.wikipedia.org/wiki/License_compatibility#Compatibility_of_FOSS_licenses

IANAL, but my understanding of how licensing compatibility and their subsumption rules work is that by using BSD3 licensed libraries you must license this utility as BSD3 or something stronger. BSD3 software can use MIT but not vice versa.

**Comment by jpvillaisaza** [comment]
@bitemyapp Thanks for bringing this up.

My understanding is that this is not a problem when dealing with BSD3 and MIT licenses because both are [permissive licenses](https://en.wikipedia.org/wiki/Permissive_software_licence) and don't impose any condition related to the license of your project, as opposed to strong copyleft licenses like GPL. Note that the licenses ([BSD3](https://choosealicense.com/licenses/bsd-3-clause/) and [MIT](https://choosealicense.com/licenses/mit/)) don't say anything about the license of your project, the conditions are only about the license and copyright notice and the permissions are basically the same. This is also the interpretation used by GitHub's [Open Source Guides](https://opensource.guide) (see [Which open source license is appropriate for my project?](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project)).
